version: '3.8'

volumes:
  static_volume:
  postgres_data:
  media_volume:

services:
  db:
    image: postgres:12.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    restart: always
    volumes:
      - ./static_volume:/code/static/
      - ./media_volume:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.4
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static_volume:/code/static/
      - ./media_volume:/code/media/
    ports:
      - '80:80'
    depends_on:
      - web