# Generated by Django 3.2 on 2021-04-23 07:40

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='наименование ингредиента')),
                ('unit', models.CharField(max_length=50, verbose_name='мера измерения')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='заголовок')),
                ('image', models.ImageField(null=True, upload_to='recipes/', verbose_name='модель изображения')),
                ('description', models.TextField(verbose_name='описание')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='время приготовления')),
                ('slug', models.SlugField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes',
                                             to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('ingredients', models.ManyToManyField(to='recipes.Ingredient', verbose_name='ингредиенты')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.',
                                                         through='taggit.TaggedItem', to='taggit.Tag',
                                                         verbose_name='Tags')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, verbose_name='количество')),
                ('ingredient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients',
                                   to='recipes.ingredient', verbose_name='ингредиент')),
                ('recipe',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients',
                                   to='recipes.recipe', verbose_name='рецепт')),
            ],
        ),
    ]
