# Generated by Django 3.1.5 on 2021-03-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_recipeingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='dimension',
            new_name='unit',
        ),
    ]
